// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8W5vpNvWIQHRRvoK8Lzp1rqstBj3q-Q',
    appId: '1:1069196299913:web:e45d6546b17fda23608058',
    messagingSenderId: '1069196299913',
    projectId: 'electrodomestico-3fff0',
    authDomain: 'electrodomestico-3fff0.firebaseapp.com',
    storageBucket: 'electrodomestico-3fff0.appspot.com',
    measurementId: 'G-Z198Z1METT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL64AnGnXP8YAWNPGv7GC7JNfz0SD7Kno',
    appId: '1:1069196299913:android:16a0352961ddcbcf608058',
    messagingSenderId: '1069196299913',
    projectId: 'electrodomestico-3fff0',
    storageBucket: 'electrodomestico-3fff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAephozsVKU1tfLRPGzgW-eseq4Nomc3jE',
    appId: '1:1069196299913:ios:2881a7ab65efe1ba608058',
    messagingSenderId: '1069196299913',
    projectId: 'electrodomestico-3fff0',
    storageBucket: 'electrodomestico-3fff0.appspot.com',
    iosBundleId: 'com.example.electrodomesticosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAephozsVKU1tfLRPGzgW-eseq4Nomc3jE',
    appId: '1:1069196299913:ios:2881a7ab65efe1ba608058',
    messagingSenderId: '1069196299913',
    projectId: 'electrodomestico-3fff0',
    storageBucket: 'electrodomestico-3fff0.appspot.com',
    iosBundleId: 'com.example.electrodomesticosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_8W5vpNvWIQHRRvoK8Lzp1rqstBj3q-Q',
    appId: '1:1069196299913:web:50925df99c6eb923608058',
    messagingSenderId: '1069196299913',
    projectId: 'electrodomestico-3fff0',
    authDomain: 'electrodomestico-3fff0.firebaseapp.com',
    storageBucket: 'electrodomestico-3fff0.appspot.com',
    measurementId: 'G-0KE0XT1ZWF',
  );

}